ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

DROP USER CP_ADMIN cascade;

CREATE USER CP_ADMIN IDENTIFIED BY 1111;
alter user CP_ADMIN quota unlimited on USERS;

GRANT CREATE SESSION TO CP_ADMIN;
grant all privileges to CP_ADMIN;
grant execute on sys.dbms_crypto to CP_ADMIN; 

-------------------------ADMIN-------------------------
CREATE PROFILE ADMIN_PROFILE LIMIT
    PASSWORD_LIFE_TIME 260
    SESSIONS_PER_USER 5
    FAILED_LOGIN_ATTEMPTS 10
    PASSWORD_LOCK_TIME 60
    CONNECT_TIME 720

CREATE ROLE ADMIN_ROLE;
GRANT CONNECT TO ADMIN_ROLE;
GRANT EXECUTE ON GENERAL_PACKAGE TO ADMIN_ROLE;
GRANT EXECUTE ON ADMIN_PACKAGE TO ADMIN_ROLE;
GRANT EXECUTE ON CLIENT_PACKAGE TO ADMIN_ROLE;

CREATE USER ADMIN IDENTIFIED BY ADMIN
PROFILE ADMIN_PROFILE;

GRANT ADMIN_ROLE TO ADMIN;

-------------------------CLIENT-------------------------
CREATE PROFILE CLIENT_PROFILE LIMIT
    PASSWORD_LIFE_TIME 260
    SESSIONS_PER_USER 100
    FAILED_LOGIN_ATTEMPTS 10
    PASSWORD_LOCK_TIME 60
    CONNECT_TIME 360
  
CREATE ROLE CLIENT_ROLE;
GRANT CONNECT TO CLIENT_ROLE;
GRANT EXECUTE ON GENERAL_PACKAGE TO CLIENT_ROLE;
GRANT EXECUTE ON CLIENT_PACKAGE TO CLIENT_ROLE;

CREATE USER CLIENT IDENTIFIED BY CLIENT
PROFILE CLIENT_PROFILE;

GRANT CLIENT_ROLE TO CLIENT;