-------------------------HASH_PASSWORD-------------------------
CREATE OR REPLACE TRIGGER HASH_PASSWORD
    BEFORE INSERT OR UPDATE OF USER_PASSWORD ON USERS FOR EACH ROW
BEGIN
    -- SHA256
    :NEW.USER_PASSWORD := DBMS_CRYPTO.HASH(UTL_RAW.CAST_TO_RAW(:NEW.USER_PASSWORD), 4);
END;
